version: "3.9"
services:
  lca:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    environment:
      - CONFIG_PATH=/config/app.yaml
    volumes:
      - ./config:/config
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: LCA
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
