package controller

const (
	// Request Errors
	INVALID_PARAM_ERROR = "INVALID_PARAM_ERROR"
	MISSING_PARAM_ERROR = "MISSING_PARAM_ERROR"
	VALIDATION_ERROR    = "VALIDATION_ERROR"

	// Auth Errors
	UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR"
	FORBIDDEN_ERROR    = "FORBIDDEN_ERROR"
	EXPIRATION_ERROR   = "EXPIRATION_ERROR"

	// Common Errors
	COMMON_INTERNAL_ERROR = "COMMON_INTERNAL_ERROR"
	COMMON_EXTERNAL_ERROR = "COMMON_EXTERNAL_ERROR"
)

const (
	// Success
	SUCCESS          = "SUCCESS"
	CREATED_SUCCESS  = "CREATED_SUCCESS"
	UPDATED_SUCCESS  = "UPDATED_SUCCESS"
	DELETED_SUCCESS  = "DELETED_SUCCESS"
	ACCEPTED_SUCCESS = "ACCEPTED_SUCCESS"
)
