app:
  run_mode: "debug"
  cancel_timeout: "5s"

server:
  http_port: 8080
  read_header_timeout: "5s"

postgresql:
  write:
    host: "postgres_write"
    port: "5432"
    user: "user"
    password: "password"
    dbname: "main"

  reads:
    - host: "postgres_read_1"
      port: "5432"
      user: "user"
      password: "password"
      dbname: "main"

    - host: "postgres_read_2"
      port: "5432"
      user: "user"
      password: "password"
      dbname: "main"

    # - host: "127.0.0.4"
    #   port: "5432"
    #   user: ""
    #   password: ""
    #   dbname: ""

    # - host: "127.0.0.5"
    #   port: "5432"
    #   user: ""
    #   password: ""
    #   dbname: ""

redis:
  master_name: "mymaster"
  write:
    addr: "redis_write:6379"
    password: ""
    db: 0
  reads:
    - addr: "redis_read_1:6379"
      password: ""
      db: 0

    - addr: "redis_read__2:6379"
      password: ""
      db: 0
  sentinel:
    - addr: "redis_sentinel_1:26379"
      password: ""
      db: 0
    - addr: "redis_sentinel_2:26379"
      password: ""
      db: 0
    - addr: "redis_sentinel_3:26379"
      password: ""
      db: 0

log:
  log_path: "./log/app.log"
  application_name: "LCA"
  debug: true

ratelimit:
  limit_per_minute: 600

jwt:
  expiration: "24h"
