app:
  run_mode: "debug"
  cancel_timeout: "5s"

server:
  http_port: 8080
  read_header_timeout: "5s"

postgresql:
  write:
    host: "127.0.0.1"
    port: "5432"
    user: ""
    password: ""
    dbname: ""

  reads:
    - host: "127.0.0.2"
      port: ""
      user: ""
      password: ""
      dbname: ""

    - host: "127.0.0.3"
      port: "5432"
      user: ""
      password: ""
      dbname: ""

    - host: "127.0.0.4"
      port: "5432"
      user: ""
      password: ""
      dbname: ""

    - host: "127.0.0.5"
      port: "5432"
      user: ""
      password: ""
      dbname: ""

redis:
  master_name:
  write:
    addr:
    password:
    db:
  reads:
    - addr:
      password:
      db:

    - addr:
      password:
      db:
  sentinel:
    - addr:
      password:
      db:
    - addr:
      password:
      db:
    - addr:
      password:
      db:
log:
  log_path: "./log/app.log"
  application_name: "LCA"
  debug: true

ratelimit:
  limit_per_minute: 600

jwt:
  expiration: "24h"
